from src.interface.api.routers import (
    admin_audit_logs,
    ai_models,
    analyses,
    auth,
    candidates,
    document_ai,
    internal_users,
    jobs,
    observability,
    pipeline,
    resumes,
    skill_equivalences,
    users,
    dashboard,
)

__all__ = [
    "auth",
    "users",
    "admin_audit_logs",
    "candidates",
    "resumes",
    "analyses",
    "jobs",
    "pipeline",
    "skill_equivalences",
    "ai_models",
    "document_ai",
    "internal_users",
    "observability",
    "dashboard",
]
