from src.interface.api.routers import (
    admin_data_quality,
    admin_scoring_comparison,
    ai_models,
    analyses,
    auth,
    candidates,
    document_ai,
    internal_users,
    jobs,
    observability,
    pipeline,
    resumes,
    skills,
    users,
)

__all__ = [
    "admin_data_quality",
    "admin_scoring_comparison",
    "auth",
    "users",
    "candidates",
    "resumes",
    "analyses",
    "jobs",
    "pipeline",
    "skills",
    "ai_models",
    "document_ai",
    "internal_users",
    "observability",
]
