"""alguma alteração

Revision ID: 18da3f050a2f
Revises: 9260624f970a
Create Date: 2026-04-23 10:36:40.896221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18da3f050a2f'
down_revision: Union[str, None] = '9260624f970a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
