"""alguma alteração

Revision ID: 9a3ccaf71f38
Revises: 18da3f050a2f
Create Date: 2026-04-23 10:39:28.059026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a3ccaf71f38'
down_revision: Union[str, None] = '18da3f050a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
