"""add_google_calendar_fields_and_table

Revision ID: 987dd5bb1da1
Revises: e8f6a1b3c9d2
Create Date: 2026-05-13 10:28:11.014822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '987dd5bb1da1'
down_revision: Union[str, None] = 'e8f6a1b3c9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_account_email', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('connected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_google_connection_user_active', 'google_calendar_connections', ['user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'), sqlite_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_google_connection_user_id', 'google_calendar_connections', ['user_id'], unique=False)
    
    op.add_column('interview_schedules', sa.Column('calendar_provider', sa.String(length=50), server_default='internal', nullable=False))
    op.add_column('interview_schedules', sa.Column('external_calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('interview_schedules', sa.Column('external_calendar_html_link', sa.Text(), nullable=True))
    op.add_column('interview_schedules', sa.Column('meeting_provider', sa.String(length=50), server_default='none', nullable=False))
    op.add_column('interview_schedules', sa.Column('calendar_sync_status', sa.String(length=50), server_default='not_synced', nullable=False))
    op.add_column('interview_schedules', sa.Column('calendar_sync_error', sa.Text(), nullable=True))
    op.add_column('interview_schedules', sa.Column('calendar_synced_at', sa.TIMESTAMP(timezone=True), nullable=True))
    
    op.create_index('idx_interview_schedules_calendar_provider_sync', 'interview_schedules', ['calendar_provider', 'calendar_sync_status'], unique=False)
    op.create_index('idx_interview_schedules_calendar_sync_status', 'interview_schedules', ['calendar_sync_status'], unique=False)
    op.create_index('idx_interview_schedules_external_calendar_event_id', 'interview_schedules', ['external_calendar_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_interview_schedules_external_calendar_event_id', table_name='interview_schedules')
    op.drop_index('idx_interview_schedules_calendar_sync_status', table_name='interview_schedules')
    op.drop_index('idx_interview_schedules_calendar_provider_sync', table_name='interview_schedules')
    
    op.drop_column('interview_schedules', 'calendar_synced_at')
    op.drop_column('interview_schedules', 'calendar_sync_error')
    op.drop_column('interview_schedules', 'calendar_sync_status')
    op.drop_column('interview_schedules', 'meeting_provider')
    op.drop_column('interview_schedules', 'external_calendar_html_link')
    op.drop_column('interview_schedules', 'external_calendar_event_id')
    op.drop_column('interview_schedules', 'calendar_provider')
    
    op.drop_index('idx_google_connection_user_id', table_name='google_calendar_connections')
    op.drop_index('idx_google_connection_user_active', table_name='google_calendar_connections', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('google_calendar_connections')
    # ### end Alembic commands ###
